#!/bin/bash
# Not sure if there's any bashisms

set -e

INCLUDE_DIRS="-I .. -I ."
for d in src ../src hal ../hal
do
    if [ -d $d ]
    then
        INCLUDE_DIRS="${INCLUDE_DIRS} -I $d"
    fi
done
echo "Guessed include dirs: ${INCLUDE_DIRS}"
GUESSED_FILE=$(echo -e "$1" | perl -lpe 's/^([^.]*)(.c?)?$/\1.c/')
echo "Guessed file: ${GUESSED_FILE}"
set -v
clang -std=c90 -ansi -Weverything -pedantic -g -c -o /dev/null "${GUESSED_FILE}" ${INCLUDE_DIRS}
