#!/bin/bash
# Not sure if there's any bashisms

set -e

FILTERS=""
if [ "$1" = "--pad" ]
then
    shift
else
    FILTERS="-Wno-padded ${FILTERS}"
fi

INCLUDE_DIRS="-I .. -I ."
for d in src ../src hal ../hal
do
    if [ -d $d ]
    then
        INCLUDE_DIRS="${INCLUDE_DIRS} -I $d"
    fi
done
echo "Guessed include dirs: ${INCLUDE_DIRS}"
GUESSED_FILE=$(echo -e "$1" | perl -lpe 's/^([^.]*)(.c?)?$/\1.c/')
echo "Guessed file: ${GUESSED_FILE}"
echo "Guessed filters: ${FILTERS}"
echo clang -std=c90 -ansi -Weverything ${FILTERS} -pedantic -g -c -o /dev/null "\"${GUESSED_FILE}\"" ${INCLUDE_DIRS}
clang -std=c90 -ansi -Weverything ${FILTERS} -pedantic -g -c -o /dev/null "${GUESSED_FILE}" ${INCLUDE_DIRS}
